export const PROBLEM_LIFECYCLE = [
  "REPORTED", "ANALYZING", "SOLUTION PROPOSED", "UNDER REVIEW", "APPROVED",
  "IN PROGRESS", "IMPLEMENTED", "VERIFICATION PENDING", "VERIFIED", "RESOLVED", "REOPENED",
];