export const ROLES = {
  government: {
    key: "government",
    title: "Government Intelligence",
    eyebrow: "Government workspace",
    tagline: "Turn regulatory complexity into evidence-based decisions.",
    loginTitle: "Welcome back",
    loginSubtitle: "Sign in to your Government Intelligence workspace.",
    emailLabel: "Official Email",
    emailPlaceholder: "name@agency.gov",
    home: "/government",
    loginPath: "/government/login",
    registerPath: "/government/register",
    forgotPath: "/government/forgot-password",
    verifyPath: "/government/verify",
    resetPath: "/government/reset-password",
    registerCta: "Create Government Account",
    createText: "Don't have an account?",
    orgGroup: "Organisation details",
    dashboardName: "Government Intelligence",
  },
  business: {
    key: "business",
    title: "Business Intelligence",
    eyebrow: "Business workspace",
    tagline: "Understand regulations. Manage risk. Plan with confidence.",
    loginTitle: "Welcome back",
    loginSubtitle: "Sign in to your Business Intelligence workspace.",
    emailLabel: "Business Email",
    emailPlaceholder: "name@company.com",
    home: "/business",
    loginPath: "/business/login",
    registerPath: "/business/register",
    forgotPath: "/business/forgot-password",
    verifyPath: "/business/verify",
    resetPath: "/business/reset-password",
    registerCta: "Create Business Account",
    createText: "New to REGULENS Business?",
    orgGroup: "Business details",
    dashboardName: "Business Intelligence",
  },
};