import { useCallback, useEffect, useState } from "react";
import { RefreshCw, Sparkles, AlertCircle } from "lucide-react";
import { SectionCard } from "@/components/business/ui/PageHeader";
import Badge from "@/components/ui/Badge";
import { bizApi, handleApiError } from "@/lib/api";

function fieldLabel(key) {
  return key
    .replace(/([A-Z])/g, " $1")
    .replace(/^./, (c) => c.toUpperCase())
    .trim();
}

function renderValue(value) {
  if (value === null || value === undefined || value === "") return null;
  if (typeof value === "object") return JSON.stringify(value);
  return String(value);
}

export default function AiInsightCard({ module, title, description, render }) {
  const [analysis, setAnalysis] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const load = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const data = await bizApi.ai({ module });
      setAnalysis(data.analysis);
    } catch (err) {
      setError(handleApiError(err));
    } finally {
      setLoading(false);
    }
  }, [module]);

  useEffect(() => {
    load();
  }, [load]);

  function renderDefault(a) {
    const sections = [];
    for (const [key, value] of Object.entries(a)) {
      if (key === "summary") continue;
      if (Array.isArray(value)) {
        if (value.length === 0) continue;
        sections.push(
          <div key={key}>
            <h3 className="mb-2 text-[11px] font-semibold uppercase tracking-wider text-ink-faint">{fieldLabel(key)}</h3>
            <ul className="space-y-2">
              {value.map((item, i) => (
                <li key={i} className="rounded-lg border border-line bg-surface-muted/40 px-3 py-2.5">
                  {typeof item === "string" ? (
                    <p className="text-sm text-ink-subtle">{item}</p>
                  ) : (
                    <div className="space-y-1">
                      {typeof item.certification === "string" || typeof item.name === "string" || typeof item.requirement === "string" || typeof item.risk === "string"
                        ? (() => {
                            const label = item.certification || item.name || item.requirement || item.risk;
                            const badge = item.mandatory ? (
                              <Badge variant="red" size="sm">Mandatory</Badge>
                            ) : item.demand ? (
                              <Badge variant={item.demand === "Regulatory" ? "red" : item.demand === "Rising" ? "blue" : "amber"} size="sm">{item.demand}</Badge>
                            ) : item.status ? (
                              <Badge variant={item.status === "Held" ? "green" : item.status === "Active" ? "green" : "neutral"} size="sm">{item.status}</Badge>
                            ) : null;
                            return (
                              <div className="flex items-center justify-between gap-2">
                                <span className="text-sm font-medium text-ink">{label}</span>
                                {badge}
                              </div>
                            );
                          })()
                        : null}
                      {Object.entries(item)
                        .filter(([k]) => !["certification", "name", "requirement", "risk", "mandatory", "demand", "status"].includes(k))
                        .map(([k, v]) => {
                          const rendered = renderValue(v);
                          if (!rendered) return null;
                          return (
                            <p key={k} className="text-xs text-ink-faint">
                              {fieldLabel(k)}: {rendered}
                            </p>
                          );
                        })}
                    </div>
                  )}
                </li>
              ))}
            </ul>
          </div>
        );
      } else if (typeof value === "number" || typeof value === "string" || typeof value === "boolean") {
        sections.push(
          <div key={key}>
            <h3 className="mb-1 text-[11px] font-semibold uppercase tracking-wider text-ink-faint">{fieldLabel(key)}</h3>
            <p className="text-sm text-ink-subtle">{renderValue(value)}</p>
          </div>
        );
      }
    }
    return (
      <div className="space-y-4">
        {a.summary && <p className="text-sm leading-relaxed text-ink">{a.summary}</p>}
        {sections}
      </div>
    );
  }

  return (
    <SectionCard
      title={title || "AI Analysis"}
      description={description || "Generated by REGULENS AI from your business data."}
      className="mb-6"
      action={
        <button
          type="button"
          onClick={load}
          disabled={loading}
          className="flex items-center gap-1.5 rounded-md border border-line px-2.5 py-1.5 text-xs font-medium text-ink-subtle transition-colors hover:border-success/50 hover:text-ink disabled:opacity-50"
        >
          <RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} aria-hidden="true" />
          {loading ? "Analyzing" : "Regenerate"}
        </button>
      }
    >
      {loading && (
        <div className="flex items-center gap-2 text-sm text-ink-subtle">
          <Sparkles className="h-4 w-4 text-success" />
          <span className="flex items-center gap-1 rounded-full bg-surface-muted px-2.5 py-1 text-xs text-ink-subtle">
            <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-success" style={{ animationDelay: "0ms" }} />
            <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-success" style={{ animationDelay: "150ms" }} />
            <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-success" style={{ animationDelay: "300ms" }} />
            Generating analysis…
          </span>
        </div>
      )}
      {!loading && error && (
        <p className="flex items-center gap-1.5 rounded-[10px] border border-danger/30 bg-danger-soft px-3.5 py-2.5 text-[13px] font-medium text-danger">
          <AlertCircle className="h-4 w-4 shrink-0" aria-hidden="true" />
          {error}
        </p>
      )}
      {!loading && !error && analysis && (typeof render === "function" ? render(analysis) : renderDefault(analysis))}
    </SectionCard>
  );
}